### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by ShaikhKabeer** [sussol/react-native-data-table#14] opened 2017-12-22 09:16 UTC
Hello , 
Is there any simple example of this library? because we don't know how to implement it.

**Comment by Chris-Petty** [comment] 2018-01-08 00:36
Hi, we haven't had a good chance to develop this this library further. I'm planning in the near future to do a rewrite to use new RN FlatList (ListView is deprecated) and make react-native-data-table not bound to using Realm as a database. There will be examples (probably a little expo one).

Duplicate of #1

**Closed by Chris-Petty** 2018-01-08 00:36 UTC
