### ISSUE TITLE
Unable to resolve module realm/react-native

### ISSUE THREAD

**Issue by jahnli** [sussol/react-native-data-table#32] opened 2018-11-29 02:46 UTC
新版的安装的时候  报错。
![image](https://user-images.githubusercontent.com/20943608/49195953-08b4b400-f3c4-11e8-88f8-e8d491b8ec2f.png)

**Comment by Chris-Petty** [comment] 2018-12-02 23:39
Duplicate of #31

**Closed by Chris-Petty** 2018-12-02 23:39 UTC
